### ISSUE TITLE
Demo & Example Code

### ISSUE THREAD

**Issue by oyeanuj** [localnerve/react-element-size-reporter#40]
Hi @localnerve, thank you for putting out this library! Could you share/publish some demos and examples of usage to understand better the functionality of the library?

**Comment by localnerve** [comment]
Hello!
Yes, one already exists and I'll add it to the readme of this project.
Here's what I was thinking of sharing. It would be helpful to me if you could give me some feedback on its usefulness:

## React-Element-Size-Reporter Demo/Example
In this example, a Page and Navigation component are covered by a background image. When the browser resizes, the background is updated.
To do this, each component that is covered by the background is wrapped in React-Element-Size-Reporter. Each component sends a size action to a store that accumulates the reports.
The store then emits an event to the background component which fetches and renders the background image.

### Staged example
*Hit the non-pwa url first and wait for the app to start (it's on a free tier)*
1. pwa-stage.herokuapp.com (non-pwa version)
2. pwa-stage.localnerve.net (pwa, but not required to see the react-element-size-reporter UI in action)

### Code
### Components wrapped in the HOC
* [Page Container Component](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/components/PageContainer.jsx#L28
)
 
* [Nav Component](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/components/header/Nav.jsx#L41)

### Store
* [Receives size action and accumulates reports](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/stores/BackgroundStore.js#L51)

### Background UI Component
* [Receives event from store and sets its own state](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/components/Background.jsx#L114)

**Comment by oyeanuj** [comment]
@localnerve Thank you for the links above. I think I understand what it does now, but I'll repeat it just to be sure I am on the right track.

1. In the demo, the component background switches from flowers to the solid color when resizing, right? So, essentially, this component is reporting when it is being resized?

2. I was a little unclear about the `store` part - did you mean a Flux/Redux `store` and if yes, does this component work best with those or can be used without those stores as well?

Hope these questions will help clear up the documentation as well!

**Comment by localnerve** [comment]
Good questions, thank you. Looks like I've got some work to do to explain better :-). Please let me know if any parts of the following explanations hit the mark.

This component is just reporting the size of the component it contains. When window resize event happens (and on ComponentDidMount initially), this component gets the new size (using [element-size-reporter](https://github.com/localnerve/element-size-reporter), creates a "report" object with the new sizes, and calls the provided "actionCreator" function passing the report object to it. Beyond that its really up to you what occurs. The demo shows just one variety of a flux-flow with actions and stores.

So, the rest of what happens is specific to a flux flow and the demo (not this component). Here is what happens in the demo:
1. The actionCreator fires the action with the payload from this component (the "size report" object).

2. The store receives the event and updates its data using the size report. The store's data are background urls. When it is done updating, it fires a "changed" event.

3. The UI component (The background component) listens for the "changed" event and reads the store to get the updated data. Then the background component makes image requests that update the background image. The data the background component gets from the store are image request urls which contain size information (these requests are made against Cloudinary, which serves appropriately sized images based on the request).

Specific Answers
1. The background component is not reporting. It just fetches urls and updates the UI. The PageContainer and Nav components are reporting their sizes to BackgroundStore. These two components together make up the size that the background image must cover. The BackgroundStore is a flux store that provides urls (with size information encoded) to the Background component. When the Background store updates, it notifies the Background component that, in turn, reads the urls from the store and fetches the images from the image service.

2. Yes I meant a flux store. If you are not interested in using a flux flow, that is OK. This component will just call whatever function you supply as the "actionCreator" with the size report object. You can do whatever you want with that data.

OK, hope this helps.

**Comment by oyeanuj** [comment]
@localnerve Thanks for the more detailed explanation - it makes more sense now. I'd suggest also incorporating this above answer in the docs/README somehow 😄
